#!/usr/bin/env bash

# Install bash functions from dotfiles
# - Copies bash functions from dotfiles/bash/ to ~/.bashrc.d/
# - Generates ~/.bashrc.d/functions.sh to source all function files
# - Ensures .bashrc sources the functions

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Determine dotfiles directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"
BASH_SRC_DIR="$DOTFILES_DIR/bash"
BASHRC_D_DIR="$HOME/.bashrc.d"
BASHRC_FILE="$HOME/.bashrc"

echo -e "${BLUE}=== Installing Bash Functions ===${NC}"
echo ""

# Create ~/.bashrc.d if it doesn't exist
if [ ! -d "$BASHRC_D_DIR" ]; then
    echo -e "${YELLOW}Creating $BASHRC_D_DIR${NC}"
    mkdir -p "$BASHRC_D_DIR"
fi

# Copy function files and build source list
function_files=()
copied_count=0

if [ ! -d "$BASH_SRC_DIR" ]; then
    echo -e "${RED}Error: $BASH_SRC_DIR does not exist${NC}"
    exit 1
fi

for src_file in "$BASH_SRC_DIR"/*.sh; do
    [ -e "$src_file" ] || continue

    filename=$(basename "$src_file")
    dest_file="$BASHRC_D_DIR/$filename"

    # Skip functions.sh to avoid overwriting the loader
    if [ "$filename" = "functions.sh" ]; then
        echo -e "${YELLOW}⊘${NC} Skipping $filename (reserved for auto-generated loader)"
        continue
    fi

    # Copy the file
    cp "$src_file" "$dest_file"
    function_files+=("$filename")
    echo -e "${GREEN}✓${NC} Copied $filename"
    copied_count=$((copied_count + 1))
done

# Generate functions.sh loader
FUNCTIONS_LOADER="$BASHRC_D_DIR/functions.sh"
echo ""
echo -e "${YELLOW}Generating $FUNCTIONS_LOADER${NC}"

cat > "$FUNCTIONS_LOADER" << 'EOF'
# Auto-generated by dotfiles/scripts/install_bash_functions.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten on next install
# To modify functions, edit files in ~/dotfiles/bash/ and re-run install_bash_functions.sh

EOF

# Add source lines for each function file
for func_file in "${function_files[@]}"; do
    echo "[ -f \"\$HOME/.bashrc.d/$func_file\" ] && source \"\$HOME/.bashrc.d/$func_file\"" >> "$FUNCTIONS_LOADER"
done

echo -e "${GREEN}✓${NC} Generated functions.sh with ${#function_files[@]} function file(s)"

# Ensure .bashrc sources functions.sh
echo ""
BASHRC_SOURCE_LINE='[ -f "$HOME/.bashrc.d/functions.sh" ] && source "$HOME/.bashrc.d/functions.sh"'

if [ -f "$BASHRC_FILE" ]; then
    if ! grep -qF '.bashrc.d/functions.sh' "$BASHRC_FILE"; then
        echo -e "${YELLOW}Adding source line to $BASHRC_FILE${NC}"
        echo "" >> "$BASHRC_FILE"
        echo "# Load custom bash functions from dotfiles" >> "$BASHRC_FILE"
        echo "$BASHRC_SOURCE_LINE" >> "$BASHRC_FILE"
        echo -e "${GREEN}✓${NC} Updated .bashrc"
    else
        echo -e "${GREEN}✓${NC} .bashrc already sources functions.sh"
    fi
else
    echo -e "${RED}✗${NC} Warning: $BASHRC_FILE not found"
fi

# Summary
echo ""
echo -e "${BLUE}=== Summary ===${NC}"
echo "  Copied: $copied_count function file(s)"
echo "  Location: $BASHRC_D_DIR/"
echo "  Loader: $BASHRC_D_DIR/functions.sh"
echo ""
echo -e "${GREEN}✓ Installation complete!${NC}"
echo -e "${YELLOW}Note: Restart your shell or run 'source ~/.bashrc' to apply changes${NC}"
